## SWAG reverse proxy config for National Armchair League
## Place this file in: /path/to/swag/config/nginx/proxy-confs/nal.subdomain.conf

server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name nal.*;

    include /config/nginx/ssl.conf;

    client_max_body_size 10M;

    location / {
        include /config/nginx/proxy.conf;
        include /config/nginx/resolver.conf;

        set $upstream_app nal;
        set $upstream_port 8000;
        set $upstream_proto http;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;
    }
}
